#!/usr/bin/env bash

# This file is part of The RetroPie Project
#
# The RetroPie Project is the legal property of its developers, whose names are
# too numerous to list here. Please refer to the COPYRIGHT.md file distributed with this source.
#
# See the LICENSE.md file at the top-level directory of this distribution and
# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
#

rp_module_id="ioquake3"
rp_module_desc="Quake 3 source port"
rp_module_licence="GPL2 https://github.com/ioquake/ioq3/blob/master/COPYING.txt"
rp_module_repo="git https://github.com/ioquake/ioq3 main"
rp_module_section="opt"
rp_module_flags="!videocore"

function depends_ioquake3() {
    getDepends cmake libsdl2-dev libgl1-mesa-dev
}

function sources_ioquake3() {
    gitPullOrClone
    # https://github.com/RetroPie/RetroPie-Setup/pull/4094
    echo 'I_ACKNOWLEDGE_THE_MAKEFILE_IS_DEPRECATED=1' >> "$md_build/Makefile"
}

function build_ioquake3() {
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    cmake --build build --clean-first
    md_ret_require="$md_build/build/Release/ioquake3"
}

function install_ioquake3() {
    md_ret_files=(
        "build/Release/ioq3ded"
        "build/Release/ioquake3"
        "build/Release/renderer_opengl1.so"
        "build/Release/renderer_opengl2.so"
        "misc/quake3.svg"
        "misc/quake3-tango.png"
    )
}

function game_data_ioquake3() {
    if [[ ! -f "$romdir/ports/quake3/pak0.pk3" ]]; then
        downloadAndExtract "$__archive_url/Q3DemoPaks.zip" "$romdir/ports/quake3" -j
    fi
    if [[ ! -f "$romdir/ports/quake3/chronic.pk3" ]]; then
        downloadAndExtract "https://raw.githubusercontent.com/RapidEdwin08/RetroPie-Setup/master/scriptmodules/ports/$md_id/$md_id-rp-assets.tar.gz" "$romdir/ports/quake3"
    fi
    # always chown as moveConfigDir in the configure_ script would move the root owned demo files
    chown -R "$__user":"$__group" "$romdir/ports/quake3"
}

function remove_ioquake3() {
    local shortcut_name
    shortcut_name="Quake III Arena"
    rm -f "/usr/share/applications/$shortcut_name.desktop"; rm -f "$home/Desktop/$shortcut_name.desktop"
    rm -f "$romdir/ports/$shortcut_name.sh"

    shortcut_name="Quake III Chronic"
    rm -f "/usr/share/applications/$shortcut_name.desktop"; rm -f "$home/Desktop/$shortcut_name.desktop"
    rm -f "$romdir/ports/$shortcut_name.sh"
}

function configure_ioquake3() {
    local launcher=("$md_inst/ioquake3")
    isPlatform "mesa" && launcher+=("+set cl_renderer opengl1")
    isPlatform "kms" && launcher+=("+set r_mode -1" "+set r_customwidth %XRES%" "+set r_customheight %YRES%" "+set r_swapInterval 1")

    addPort "$md_id" "quake3" "Quake III Arena" "${launcher[*]}"

    # [+set g_gametype] 0 = deathmatch # 1 = one on one (tournament) # 2 = single player deathmatch # 3 = team deathmatch # 4 = capture the flag
    launcher+=("+map chronic +set g_gametype 0 +bot_enable 1 +addbot eminem 3 red +addbot dre blue")
    addPort "$md_id-chronic" "quake3-chronic" "Quake III Chronic" "${launcher[*]}"

    mkRomDir "ports/quake3"

    moveConfigDir "$md_inst/baseq3" "$romdir/ports/quake3"
    moveConfigDir "$home/.q3a" "$md_conf_root/quake3/ioquake3"
    mkUserDir "$md_conf_root/quake3/ioquake3/baseq3"

    cat >"$md_inst/q3config.cfg" << _EOF_
// generated by quake, do not modify
unbindall
bind TAB "+scores"
bind ENTER "+button2"
bind ESCAPE "togglemenu"
bind SPACE "+moveup"
bind + "sizeup"
bind - "sizedown"
bind / "weapnext"
bind 0 "weapon 10"
bind 1 "weapon 1"
bind 2 "weapon 2"
bind 3 "weapon 3"
bind 4 "weapon 4"
bind 5 "weapon 5"
bind 6 "weapon 6"
bind 7 "weapon 7"
bind 8 "weapon 8"
bind 9 "weapon 9"
bind = "sizeup"
bind [ "weapprev"
bind \ "+mlook"
bind ] "weapnext"
bind _ "sizedown"
bind \` "toggleconsole"
bind a "+moveleft"
bind c "+movedown"
bind d "+moveright"
bind s "+back"
bind t "messagemode"
bind w "+forward"
bind ~ "toggleconsole"
bind PAUSE "pause"
bind UPARROW "+forward"
bind DOWNARROW "+back"
bind LEFTARROW "+left"
bind RIGHTARROW "+right"
bind ALT "+strafe"
bind CTRL "+attack"
bind SHIFT "+speed"
bind DEL "+lookdown"
bind PGDN "+lookup"
bind END "centerview"
bind F1 "vote yes"
bind F2 "vote no"
bind F3 "ui_teamorders"
bind F11 "screenshot"
bind MOUSE1 "+attack"
bind MOUSE2 "+strafe"
bind MOUSE3 "+zoom"
bind MWHEELDOWN "weapnext"
bind MWHEELUP "weapprev"
bind PAD0_A "+moveup"
bind PAD0_B "centerview"
bind PAD0_X "+movedown"
bind PAD0_Y "+speed"
bind PAD0_BACK "+scores"
bind PAD0_START "togglemenu"
bind PAD0_LEFTSTICK_CLICK "+movedown"
bind PAD0_RIGHTSTICK_CLICK "centerview"
bind PAD0_LEFTSHOULDER "+zoom"
bind PAD0_RIGHTSHOULDER "weapnext"
bind PAD0_DPAD_UP "+button3"
bind PAD0_DPAD_DOWN "+button2"
bind PAD0_DPAD_LEFT "weapprev"
bind PAD0_DPAD_RIGHT "weapnext"
bind PAD0_LEFTSTICK_LEFT "+moveleft"
bind PAD0_LEFTSTICK_RIGHT "+moveright"
bind PAD0_LEFTSTICK_UP "+forward"
bind PAD0_LEFTSTICK_DOWN "+back"
bind PAD0_RIGHTSTICK_LEFT "+left"
bind PAD0_RIGHTSTICK_RIGHT "+right"
bind PAD0_RIGHTSTICK_UP "+lookup"
bind PAD0_RIGHTSTICK_DOWN "+lookdown"
bind PAD0_LEFTTRIGGER "+moveup"
bind PAD0_RIGHTTRIGGER "+attack"
seta com_hunkMegs "128"
seta com_altivec "0"
seta com_maxfps "85"
seta com_blood "1"
seta com_ansiColor "0"
seta com_maxfpsUnfocused "0"
seta com_maxfpsMinimized "0"
seta com_busyWait "0"
seta com_introplayed "1"
seta con_autochat "1"
seta vm_cgame "2"
seta vm_game "2"
seta vm_ui "2"
seta dmflags "0"
seta fraglimit "10"
seta timelimit "0"
seta sv_hostname "noname"
seta sv_maxclients "8"
seta sv_minRate "0"
seta sv_maxRate "0"
seta sv_dlRate "100"
seta sv_minPing "0"
seta sv_maxPing "0"
seta sv_floodProtect "1"
seta sv_dlURL ""
seta sv_master3 ""
seta sv_master4 ""
seta sv_master5 ""
seta sv_lanForceRate "1"
seta sv_strictAuth "1"
seta sv_banFile "serverbans.dat"
seta con_autoclear "1"
seta cl_timedemoLog ""
seta cl_autoRecordDemo "0"
seta cl_aviFrameRate "25"
seta cl_aviMotionJpeg "1"
seta cl_yawspeed "140"
seta cl_pitchspeed "140"
seta cl_maxpackets "30"
seta cl_packetdup "1"
seta cl_run "1"
seta sensitivity "5"
seta cl_mouseAccel "0"
seta cl_freelook "1"
seta cl_mouseAccelStyle "0"
seta cl_mouseAccelOffset "5"
seta cl_allowDownload "0"
seta r_inGameVideo "1"
seta cg_autoswitch "1"
seta m_pitch "0.022000"
seta m_yaw "0.022"
seta m_forward "0.25"
seta m_side "0.25"
seta m_filter "0"
seta j_pitch "0.022"
seta j_yaw "-0.022"
seta j_forward "-0.25"
seta j_side "0.25"
seta j_up "0"
seta j_pitch_axis "3"
seta j_yaw_axis "2"
seta j_forward_axis "1"
seta j_side_axis "0"
seta j_up_axis "4"
seta cl_maxPing "800"
seta cl_lanForcePackets "1"
seta cl_guidServerUniq "1"
seta cl_consoleKeys "~ \` 0x7e 0x60"
seta name "Quake Guy"
seta rate "25000"
seta snaps "20"
seta model "sarge"
seta headmodel "sarge"
seta team_model "james"
seta team_headmodel "*james"
seta g_redTeam "Stroggs"
seta g_blueTeam "Pagans"
seta color1 "4"
seta color2 "5"
seta handicap "100"
seta sex "male"
seta cl_anonymous "0"
seta cg_predictItems "1"
seta cl_useMumble "0"
seta cl_mumbleScale "0.0254"
seta cl_voipGainDuringCapture "0.2"
seta cl_voipCaptureMult "2.0"
seta cl_voipUseVAD "0"
seta cl_voipVADThreshold "0.25"
seta cl_voipShowMeter "1"
seta cl_voip "1"
seta cl_cURLLib "libcurl.so.4"
seta cg_viewsize "100"
seta cg_stereoSeparation "0"
seta cl_renderer "opengl2"
seta r_allowExtensions "1"
seta r_ext_compressed_textures "0"
seta r_ext_multitexture "1"
seta r_ext_compiled_vertex_array "1"
seta r_ext_texture_env_add "1"
seta r_ext_framebuffer_object "1"
seta r_ext_texture_float "1"
seta r_ext_framebuffer_multisample "0"
seta r_arb_seamless_cube_map "0"
seta r_arb_vertex_array_object "1"
seta r_ext_direct_state_access "1"
seta r_ext_texture_filter_anisotropic "0"
seta r_ext_max_anisotropy "2"
seta r_picmip "1"
seta r_roundImagesDown "1"
seta r_detailtextures "1"
seta r_texturebits "0"
seta r_colorbits "0"
seta r_stencilbits "8"
seta r_depthbits "0"
seta r_ext_multisample "0"
seta r_overBrightBits "1"
seta r_ignorehwgamma "0"
seta r_mode "-2"
seta r_fullscreen "1"
seta r_noborder "0"
seta r_customwidth "1600"
seta r_customheight "1024"
seta r_customPixelAspect "1"
seta r_simpleMipMaps "1"
seta r_vertexLight "0"
seta r_subdivisions "4"
seta r_stereoEnabled "0"
seta r_greyscale "0"
seta r_hdr "1"
seta r_floatLightmap "0"
seta r_postProcess "1"
seta r_toneMap "1"
seta r_autoExposure "1"
seta r_depthPrepass "1"
seta r_ssao "0"
seta r_normalMapping "1"
seta r_specularMapping "1"
seta r_deluxeMapping "1"
seta r_parallaxMapping "0"
seta r_parallaxMapOffset "0"
seta r_parallaxMapShadows "0"
seta r_cubeMapping "0"
seta r_cubemapSize "128"
seta r_deluxeSpecular "0.3"
seta r_pbr "0"
seta r_baseNormalX "1.0"
seta r_baseNormalY "1.0"
seta r_baseParallax "0.05"
seta r_baseSpecular "0.04"
seta r_baseGloss "0.3"
seta r_glossType "1"
seta r_dlightMode "0"
seta r_pshadowDist "128"
seta r_mergeLightmaps "1"
seta r_imageUpsample "0"
seta r_imageUpsampleMaxSize "1024"
seta r_imageUpsampleType "1"
seta r_genNormalMaps "0"
seta r_drawSunRays "0"
seta r_sunlightMode "1"
seta r_sunShadows "1"
seta r_shadowFilter "1"
seta r_shadowBlur "0"
seta r_shadowMapSize "1024"
seta r_shadowCascadeZNear "8"
seta r_shadowCascadeZFar "1024"
seta r_shadowCascadeZBias "0"
seta r_ignoreDstAlpha "1"
seta r_lodCurveError "250"
seta r_lodbias "0"
seta r_flares "0"
seta r_zproj "64"
seta r_stereoSeparation "64"
seta r_ignoreGLErrors "1"
seta r_fastsky "0"
seta r_drawSun "0"
seta r_dynamiclight "1"
seta r_dlightBacks "1"
seta r_finish "0"
seta r_textureMode "GL_LINEAR_MIPMAP_LINEAR"
seta r_swapInterval "0"
seta r_gamma "1"
seta r_facePlaneCull "1"
seta r_railWidth "16"
seta r_railCoreWidth "6"
seta r_railSegmentLength "32"
seta r_anaglyphMode "0"
seta cg_shadows "1"
seta r_marksOnTriangleMeshes "0"
seta r_vaoCache "0"
seta r_aviMotionJpegQuality "90"
seta r_screenshotJpegQuality "90"
seta r_allowResize "0"
seta r_centerWindow "0"
seta r_preferOpenGLES "-1"
seta in_keyboardDebug "0"
seta in_mouse "1"
seta in_nograb "0"
seta in_joystick "1"
seta joy_threshold "0.150000"
seta s_volume "0.8"
seta s_musicvolume "0.25"
seta s_doppler "1"
seta s_muteWhenMinimized "0"
seta s_muteWhenUnfocused "0"
seta s_useOpenAL "1"
seta s_alPrecache "1"
seta s_alGain "1.0"
seta s_alSources "96"
seta s_alDopplerFactor "1.0"
seta s_alDopplerSpeed "9000"
seta s_alDriver "libopenal.so.1"
seta s_alInputDevice ""
seta s_alDevice ""
seta s_alCapture "1"
seta ui_ffa_fraglimit "20"
seta ui_ffa_timelimit "0"
seta ui_tourney_fraglimit "0"
seta ui_tourney_timelimit "15"
seta ui_team_fraglimit "0"
seta ui_team_timelimit "20"
seta ui_team_friendly "1"
seta ui_ctf_capturelimit "8"
seta ui_ctf_timelimit "30"
seta ui_ctf_friendly "0"
seta g_spScores1 ""
seta g_spScores2 ""
seta g_spScores3 ""
seta g_spScores4 ""
seta g_spScores5 ""
seta g_spAwards ""
seta g_spVideos ""
seta g_spSkill "2"
seta ui_browserMaster "0"
seta ui_browserGameType "0"
seta ui_browserSortKey "4"
seta ui_browserShowFull "1"
seta ui_browserShowEmpty "1"
seta cg_brassTime "2500"
seta cg_drawCrosshair "4"
seta cg_drawCrosshairNames "1"
seta cg_marks "1"
seta server1 ""
seta server2 ""
seta server3 ""
seta server4 ""
seta server5 ""
seta server6 ""
seta server7 ""
seta server8 ""
seta server9 ""
seta server10 ""
seta server11 ""
seta server12 ""
seta server13 ""
seta server14 ""
seta server15 ""
seta server16 ""
seta com_pipefile ""
seta net_enabled "3"
seta net_mcast6addr "ff04::696f:7175:616b:6533"
seta net_mcast6iface ""
seta net_socksEnabled "0"
seta net_socksServer ""
seta net_socksPort "1080"
seta net_socksUsername ""
seta net_socksPassword ""
seta cm_playerCurveClip "1"
seta g_maxGameClients "0"
seta capturelimit "8"
seta g_friendlyFire "0"
seta g_teamAutoJoin "0"
seta g_teamForceBalance "0"
seta g_warmup "20"
seta g_log "games.log"
seta g_logSync "0"
seta g_banIPs ""
seta g_filterBan "1"
seta g_allowVote "1"
seta cg_drawGun "1"
seta cg_zoomfov "22.5"
seta cg_fov "90"
seta cg_gibs "1"
seta cg_draw2D "1"
seta cg_drawStatus "1"
seta cg_drawTimer "0"
seta cg_drawFPS "0"
seta cg_drawSnapshot "0"
seta cg_draw3dIcons "1"
seta cg_drawIcons "1"
seta cg_drawAmmoWarning "1"
seta cg_drawAttacker "1"
seta cg_drawRewards "1"
seta cg_crosshairSize "24"
seta cg_crosshairHealth "1"
seta cg_crosshairX "0"
seta cg_crosshairY "0"
seta cg_simpleItems "0"
seta cg_lagometer "1"
seta cg_railTrailTime "400"
seta cg_runpitch "0.002"
seta cg_runroll "0.005"
seta cg_bobpitch "0.002"
seta cg_bobroll "0.002"
seta cg_teamChatTime "3000"
seta cg_teamChatHeight "0"
seta cg_forceModel "0"
seta cg_deferPlayers "1"
seta cg_drawTeamOverlay "0"
seta cg_drawFriend "1"
seta cg_teamChatsOnly "0"
seta cg_noVoiceChats "0"
seta cg_noVoiceText "0"
seta cg_cameraOrbitDelay "50"
seta cg_scorePlums "1"
seta cg_smoothClients "0"
seta cg_noTaunt "0"
seta cg_noProjectileTrail "0"
seta ui_smallFont "0.25"
seta ui_bigFont "0.4"
seta cg_oldRail "1"
seta cg_oldRocket "1"
seta cg_oldPlasma "1"
seta cg_trueLightning "0.0"
seta in_joystickNo "0"
seta in_joystickUseAnalog "0"
seta com_zoneMegs "24"
_EOF_
    if [[ ! -f "$md_conf_root/quake3/ioquake3/baseq3/q3config.cfg" ]]; then cp "$md_inst/q3config.cfg" "$md_conf_root/quake3/ioquake3/baseq3/q3config.cfg"; fi
    if [[ ! -f "$md_conf_root/quake3/ioquake3/baseq3/q3config.cfg.ioquake3" ]]; then cp "$md_inst/q3config.cfg" "$md_conf_root/quake3/ioquake3/baseq3/q3config.cfg.ioquake3"; fi
    sed -i s+seta\ in_joystick.*+seta\ in_joystick\ \"1\"+ "$md_conf_root/quake3/ioquake3/baseq3/q3config.cfg"
    chown $__user:$__user "$md_conf_root/quake3/ioquake3/baseq3/q3config.cfg"
    chown $__user:$__user "$md_conf_root/quake3/ioquake3/baseq3/q3config.cfg.ioquake3"

    [[ "$md_mode" == "install" ]] && game_data_ioquake3
    [[ "$md_mode" == "install" ]] && shortcuts_icons_ioquake3
    [[ "$md_mode" == "remove" ]] && remove_ioquake3
}

function shortcuts_icons_ioquake3() {
    local launcher=("$md_inst/ioquake3")
    isPlatform "mesa" && launcher+=("+set cl_renderer opengl1")
    isPlatform "kms" && launcher+=("+set r_mode -1" "+set r_swapInterval 1")

    local shortcut_name
    shortcut_name="Quake III Arena"
    cat >"$md_inst/$shortcut_name.desktop" << _EOF_
[Desktop Entry]
Name=$shortcut_name
GenericName=$shortcut_name
Comment=$shortcut_name
Exec=${launcher[*]}
Icon=$md_inst/quake3.svg
Terminal=false
Type=Application
Categories=Game;Emulator
Keywords=Q3;QuakeIII;Arena
StartupWMClass=QuakeIIIArena
Name[en_US]=$shortcut_name
_EOF_
    chmod 755 "$md_inst/$shortcut_name.desktop"
    if [[ -d "$home/Desktop" ]]; then rm -f "$home/Desktop/$shortcut_name.desktop"; cp "$md_inst/$shortcut_name.desktop" "$home/Desktop/$shortcut_name.desktop"; chown $__user:$__user "$home/Desktop/$shortcut_name.desktop"; fi
    rm -f "/usr/share/applications/$shortcut_name.desktop"; cp "$md_inst/$shortcut_name.desktop" "/usr/share/applications/$shortcut_name.desktop"; chown $__user:$__user "/usr/share/applications/$shortcut_name.desktop"

    # [+set g_gametype] 0 = deathmatch # 1 = one on one (tournament) # 2 = single player deathmatch # 3 = team deathmatch # 4 = capture the flag
    launcher+=("+map chronic +set g_gametype 0 +bot_enable 1 +addbot eminem 3 red +addbot dre blue")
    shortcut_name="Quake III Chronic"
    cat >"$md_inst/$shortcut_name.desktop" << _EOF_
[Desktop Entry]
Name=$shortcut_name
GenericName=$shortcut_name
Comment=A Single Map featuring Eminem & Dr. Dre
Exec=${launcher[*]}
Icon=$md_inst/quake3chronic_72x72.xpm
Terminal=false
Type=Application
Categories=Game;Emulator
Keywords=Q3;QuakeIII;Chronic
StartupWMClass=QuakeIIIChronic
Name[en_US]=$shortcut_name
_EOF_
    chmod 755 "$md_inst/$shortcut_name.desktop"
    if [[ -d "$home/Desktop" ]]; then rm -f "$home/Desktop/$shortcut_name.desktop"; cp "$md_inst/$shortcut_name.desktop" "$home/Desktop/$shortcut_name.desktop"; chown $__user:$__user "$home/Desktop/$shortcut_name.desktop"; fi
    rm -f "/usr/share/applications/$shortcut_name.desktop"; cp "$md_inst/$shortcut_name.desktop" "/usr/share/applications/$shortcut_name.desktop"; chown $__user:$__user "/usr/share/applications/$shortcut_name.desktop"

    cat >"$md_inst/quake3chronic_72x72.xpm" << _EOF_
/* XPM */
static char * quake3chronic_72x72_xpm[] = {
"72 72 551 2",
"   c None",
".  c #0A1D0C",
"+  c #0A1F0D",
"@  c #0B240E",
"#  c #0D2910",
"\$     c #143F19",
"%  c #071809",
"&  c #113415",
"*  c #1B5522",
"=  c #16441B",
"-  c #1F5F26",
";  c #081809",
">  c #091D0B",
",  c #236B2B",
"'  c #08190A",
")  c #1E5E26",
"!  c #26732F",
"~  c #091B0B",
"{  c #091C0B",
"]  c #26732E",
"^  c #297C33",
"/  c #091D0C",
"(  c #2E8638",
"_  c #2D8938",
":  c #0A200D",
"<  c #020602",
"[  c #3C9346",
"}  c #308D3B",
"|  c #030C04",
"1  c #0A1F0C",
"2  c #4FA559",
"3  c #318E3C",
"4  c #113615",
"5  c #041005",
"6  c #0C270F",
"7  c #60B269",
"8  c #328C3C",
"9  c #15411A",
"0  c #051306",
"a  c #103314",
"b  c #6EBD76",
"c  c #31873A",
"d  c #194D1F",
"e  c #061507",
"f  c #79C782",
"g  c #2F8339",
"h  c #1D5C25",
"i  c #071708",
"j  c #184D1E",
"k  c #85CF8D",
"l  c #2E7F37",
"m  c #206127",
"n  c #091C0C",
"o  c #1E6226",
"p  c #8CD494",
"q  c #2D7C36",
"r  c #22682A",
"s  c #081A0A",
"t  c #216D2A",
"u  c #96DA9D",
"v  c #2C7A35",
"w  c #246E2D",
"x  c #2E7E37",
"y  c #9BDDA2",
"z  c #2B7834",
"A  c #256E2D",
"B  c #010401",
"C  c #3E8E47",
"D  c #9FDEA6",
"E  c #2B7633",
"F  c #27742F",
"G  c #030903",
"H  c #0A1E0C",
"I  c #133917",
"J  c #4C9C54",
"K  c #A2DFA9",
"L  c #2A7432",
"M  c #25712E",
"N  c #0E2B11",
"O  c #040D05",
"P  c #0F2F13",
"Q  c #15401A",
"R  c #0B230E",
"S  c #103113",
"T  c #216529",
"U  c #194C1E",
"V  c #071608",
"W  c #5CAE65",
"X  c #A1DFA8",
"Y  c #297231",
"Z  c #236A2C",
"\`     c #144019",
" . c #051106",
".. c #103214",
"+. c #22672A",
"@. c #184C1E",
"#. c #184A1E",
"\$.    c #2A7E34",
"%. c #184A1D",
"&. c #091A0A",
"*. c #0D2A11",
"=. c #6DB875",
"-. c #286F30",
";. c #22652A",
">. c #194F1F",
",. c #061307",
"'. c #0D2810",
"). c #267430",
"!. c #22692B",
"~. c #0B220D",
"{. c #174A1D",
"]. c #2E8B39",
"^. c #1B5622",
"/. c #081B0A",
"(. c #020803",
"_. c #133E18",
":. c #76C27E",
"<. c #9DDEA5",
"[. c #276D2F",
"}. c #1F5E26",
"|. c #1C5723",
"1. c #0F3013",
"2. c #2B8135",
"3. c #0D2B11",
"4. c #409A4A",
"5. c #2C8236",
"6. c #000000",
"7. c #194E1F",
"8. c #80C988",
"9. c #276C2F",
"0. c #1C5523",
"a. c #206428",
"b. c #1A5221",
"c. c #297B33",
"d. c #1A5120",
"e. c #216229",
"f. c #65BC6E",
"g. c #071709",
"h. c #89D091",
"i. c #98DCA0",
"j. c #266A2E",
"k. c #1A4F20",
"l. c #226A2B",
"m. c #44964D",
"n. c #71BB79",
"o. c #0F3113",
"p. c #040F05",
"q. c #8ED796",
"r. c #96DB9D",
"s. c #25682D",
"t. c #194C20",
"u. c #236C2C",
"v. c #246D2C",
"w. c #22662A",
"x. c #15431B",
"y. c #061508",
"z. c #54A55D",
"A. c #71B978",
"B. c #0F2F12",
"C. c #061407",
"D. c #95DA9D",
"E. c #92DA9B",
"F. c #24652B",
"G. c #194A1E",
"H. c #256F2D",
"I. c #246D2D",
"J. c #1D5824",
"K. c #3A8D43",
"L. c #88D190",
"M. c #2F7E38",
"N. c #091B0A",
"O. c #2E8538",
"P. c #97DC9F",
"Q. c #8ED897",
"R. c #22622A",
"S. c #18491E",
"T. c #256F2E",
"U. c #1D5B24",
"V. c #1B5421",
"W. c #4D9354",
"X. c #7ACA83",
"Y. c #54A75D",
"Z. c #15421A",
"\`.    c #0C240E",
" + c #44944D",
".+ c #94DB9C",
"++ c #8AD793",
"@+ c #215F28",
"#+ c #18481E",
"\$+    c #0D2C11",
"%+ c #0B210D",
"&+ c #123A17",
"*+ c #2C8537",
"=+ c #297B32",
"-+ c #0E2E12",
";+ c #051006",
">+ c #25722E",
",+ c #2B6F33",
"'+ c #69B371",
")+ c #84D28C",
"!+ c #74C47D",
"~+ c #55AA5E",
"{+ c #398E42",
"]+ c #276E2F",
"^+ c #1C5924",
"/+ c #15441B",
"(+ c #529F5A",
"_+ c #91DA9A",
":+ c #86D58F",
"<+ c #205C27",
"[+ c #246C2C",
"}+ c #103515",
"|+ c #050F06",
"1+ c #22682B",
"2+ c #2E8438",
"3+ c #3D9D48",
"4+ c #3DA74A",
"5+ c #31913C",
"6+ c #1F5D26",
"7+ c #17441C",
"8+ c #010301",
"9+ c #081A0B",
"0+ c #2B6E33",
"a+ c #65A96C",
"b+ c #96DC9F",
"c+ c #8ED997",
"d+ c #83D08B",
"e+ c #77C880",
"f+ c #6BBD74",
"g+ c #61B169",
"h+ c #52A95C",
"i+ c #4A9C52",
"j+ c #428F4B",
"k+ c #378840",
"l+ c #2C8136",
"m+ c #277931",
"n+ c #246F2D",
"o+ c #206328",
"p+ c #1E6026",
"q+ c #1E5F26",
"r+ c #0C250F",
"s+ c #0D2A10",
"t+ c #59AF62",
"u+ c #8DD996",
"v+ c #81D48B",
"w+ c #1F5A26",
"x+ c #18471D",
"y+ c #15431A",
"z+ c #051307",
"A+ c #1F6026",
"B+ c #236C2B",
"C+ c #246F2C",
"D+ c #287B31",
"E+ c #32873C",
"F+ c #3B8D44",
"G+ c #40984A",
"H+ c #46A451",
"I+ c #4FAB59",
"J+ c #56B561",
"K+ c #5DBF68",
"L+ c #64C56F",
"M+ c #5ABE65",
"N+ c #48A152",
"O+ c #327B3A",
"P+ c #16411B",
"Q+ c #1B5322",
"R+ c #26722F",
"S+ c #206128",
"T+ c #1D5524",
"U+ c #3E7F45",
"V+ c #6AAC71",
"W+ c #84CB8C",
"X+ c #92D99B",
"Y+ c #96DC9E",
"Z+ c #95DC9D",
"\`+    c #92DB9B",
" @ c #8FDA98",
".@ c #8CD895",
"+@ c #88D692",
"@@ c #86D590",
"#@ c #86D48F",
"\$@    c #82D38B",
"%@ c #7ED187",
"&@ c #52AE5C",
"*@ c #0E2D11",
"=@ c #62B56C",
"-@ c #89D892",
";@ c #7DD287",
">@ c #1E5825",
",@ c #17461D",
"'@ c #287831",
")@ c #78CF82",
"!@ c #79D083",
"~@ c #77D082",
"{@ c #76D081",
"]@ c #77D181",
"^@ c #76D181",
"/@ c #77D282",
"(@ c #76D180",
"_@ c #72CE7D",
":@ c #66C171",
"<@ c #53A35C",
"[@ c #317639",
"}@ c #194A1F",
"|@ c #1B5221",
"1@ c #0E2C11",
"2@ c #020702",
"3@ c #1C5622",
"4@ c #1C5422",
"5@ c #296730",
"6@ c #498D51",
"7@ c #62A96A",
"8@ c #74C07C",
"9@ c #80D089",
"0@ c #89D792",
"a@ c #8ED996",
"b@ c #8CD995",
"c@ c #8BD894",
"d@ c #8AD893",
"e@ c #52A55B",
"f@ c #071508",
"g@ c #14411A",
"h@ c #66BF70",
"i@ c #84D68E",
"j@ c #78D082",
"k@ c #1C5423",
"l@ c #17451D",
"m@ c #1C5623",
"n@ c #1D5A24",
"o@ c #23692B",
"p@ c #75D080",
"q@ c #7BD386",
"r@ c #7AD285",
"s@ c #79D284",
"t@ c #78D282",
"u@ c #70CF7B",
"v@ c #68C773",
"w@ c #5CB867",
"x@ c #4EA158",
"y@ c #3A8543",
"z@ c #226229",
"A@ c #16421B",
"B@ c #206227",
"C@ c #000100",
"D@ c #051005",
"E@ c #133D18",
"F@ c #206228",
"G@ c #1A4D20",
"H@ c #24622B",
"I@ c #33803C",
"J@ c #46924F",
"K@ c #56A55F",
"L@ c #60B16A",
"M@ c #6ABC73",
"N@ c #7FD389",
"O@ c #85D68F",
"P@ c #45964E",
"Q@ c #184D1F",
"R@ c #69C574",
"S@ c #7FD489",
"T@ c #72CE7C",
"U@ c #1B5222",
"V@ c #17451C",
"W@ c #1A4E20",
"X@ c #1F6127",
"Y@ c #6ACB75",
"Z@ c #75D180",
"\`@    c #71CE7B",
" # c #4CA356",
".# c #3C8D45",
"+# c #2C7B35",
"@# c #215E28",
"## c #184A1F",
"\$#    c #16441C",
"%# c #16431B",
"&# c #1A4F21",
"*# c #123B17",
"=# c #1D5924",
"-# c #16431C",
";# c #68BF72",
"># c #80D58A",
",# c #7ED488",
"'# c #338D3D",
")# c #061408",
"!# c #64C46F",
"~# c #7AD284",
"{# c #6CCC77",
"]# c #1A4C1F",
"^# c #216428",
"/# c #1B5422",
"(# c #61C16C",
"_# c #6FCF7A",
":# c #67C772",
"<# c #1F6027",
"[# c #000101",
"}# c #216429",
"|# c #63B96D",
"1# c #7BD385",
"2# c #78D182",
"3# c #287932",
"4# c #5ABA65",
"5# c #74D07F",
"6# c #67C872",
"7# c #194C1F",
"8# c #184E1F",
"9# c #56BB62",
"0# c #68CD74",
"a# c #60C36B",
"b# c #081909",
"c# c #030B04",
"d# c #010201",
"e# c #0C2810",
"f# c #22692A",
"g# c #5EB368",
"h# c #6ECD79",
"i# c #040E05",
"j# c #50AF5B",
"k# c #6ECE79",
"l# c #61C56D",
"m# c #1E5C25",
"n# c #4CB358",
"o# c #62CB6E",
"p# c #57BF63",
"q# c #18491D",
"r# c #25702E",
"s# c #040D04",
"t# c #57AD61",
"u# c #62C86E",
"v# c #030A04",
"w# c #44A64F",
"x# c #67CC73",
"y# c #5BC167",
"z# c #216328",
"A# c #051206",
"B# c #0E2D12",
"C# c #45AA50",
"D# c #5AC867",
"E# c #4EBB5A",
"F# c #17471D",
"G# c #020502",
"H# c #061608",
"I# c #16401B",
"J# c #4EA859",
"K# c #5ABF66",
"L# c #3B9746",
"M# c #60CA6C",
"N# c #55BE61",
"O# c #236A2B",
"P# c #030A03",
"Q# c #3AA347",
"R# c #53C660",
"S# c #46B453",
"T# c #103213",
"U# c #45A450",
"V# c #62CA6E",
"W# c #4FB95B",
"X# c #051207",
"Y# c #308C3B",
"Z# c #58C765",
"\`#    c #4EB95A",
" \$    c #33953F",
".\$    c #4BC359",
"+\$    c #3FAD4C",
"@\$    c #1A5021",
"#\$    c #1E5D25",
"\$\$   c #0C260F",
"%\$    c #3E9C49",
"&\$    c #46B253",
"*\$    c #287B32",
"=\$    c #50C45E",
"-\$    c #46B553",
";\$    c #2D8637",
">\$    c #42C051",
",\$    c #38A645",
"'\$    c #15411B",
")\$    c #19501F",
"!\$    c #389343",
"~\$    c #52C560",
"{\$    c #3FA84B",
"]\$    c #0F2E12",
"^\$    c #46C054",
"/\$    c #3EB04C",
"(\$    c #010402",
"_\$    c #297E33",
":\$    c #3DB64B",
"<\$    c #349D40",
"[\$    c #133C18",
"}\$    c #328B3D",
"|\$    c #4AC358",
"1\$    c #37A144",
"2\$    c #3EB74C",
"3\$    c #39AA46",
"4\$    c #236B2C",
"5\$    c #081B0B",
"6\$    c #39AC47",
"7\$    c #30923C",
"8\$    c #153F1A",
"9\$    c #040C04",
"0\$    c #2C8437",
"a\$    c #31923C",
"b\$    c #010502",
"c\$    c #35A142",
"d\$    c #36A142",
"e\$    c #2D8737",
"f\$    c #153E1A",
"g\$    c #287A32",
"h\$    c #3DB84C",
"i\$    c #2C8436",
"j\$    c #32963E",
"k\$    c #153E19",
"l\$    c #1E5E25",
"m\$    c #32973E",
"n\$    c #143E19",
"o\$    c #17491D",
"p\$    c #3AAD48",
"q\$    c #2F8D3A",
"r\$    c #308F3B",
"s\$    c #216329",
"t\$    c #36A343",
"u\$    c #2C8336",
"v\$    c #143C19",
"w\$    c #1E5D26",
"x\$    c #2D8838",
"y\$    c #194D20",
"z\$    c #33983F",
"A\$    c #2D8738",
"B\$    c #144119",
"C\$    c #113816",
"D\$    c #1E5B25",
"E\$    c #1A5220",
"F\$    c #308E3A",
"G\$    c #297A32",
"H\$    c #143B18",
"I\$    c #1B5121",
"J\$    c #143F18",
"K\$    c #26742F",
"L\$    c #133A18",
"M\$    c #277530",
"N\$    c #2A7F34",
"O\$    c #133918",
"P\$    c #1A5321",
"Q\$    c #26712F",
"R\$    c #020703",
"S\$    c #1D5B25",
"T\$    c #216629",
"U\$    c #206027",
"V\$    c #16471C",
"W\$    c #2A8035",
"X\$    c #123916",
"Y\$    c #1B5321",
"Z\$    c #010101",
"                                                                                                                                                ",
"                                                                        .                                                                       ",
"                                                                      + @                                                                       ",
"                                                                      # \$ %                                                                     ",
"                                                                      & * %                                                                     ",
"                                                                      = - ;                                                                     ",
"                                                                    > * , '                                                                     ",
"                                                                    > ) ! ~                                                                     ",
"                                                                    { ] ^ {                                                                     ",
"                                                                    / ( _ : <                                                                   ",
"                                                                    . [ } # |                                                                   ",
"                                                                    1 2 3 4 5                                                                   ",
"                                                                    6 7 8 9 0                                                                   ",
"                                                                    a b c d e                                                                   ",
"                                                                    \$ f g h i                                                                   ",
"                                                                    j k l m ;                                                                   ",
"                                                                  n o p q r s                                                                   ",
"                                                                  / t u v w ~                                                                   ",
"                                                                  { x y z A / B                                                                 ",
"                      / >                                         / C D E F : G                                       H / >                     ",
"                  . 4 I :                                         . J K L M N O                                       / P Q R {                 ",
"              H S T U / V                                         1 W X Y Z \`  .                                        { ..+.@.H               ",
"            . #.\$.%.&.|                                           *.=.D -.;.>.,.                                          ' '.).!.~.            ",
"          H {.].^./.(.                                            _.:.<.[.}.|.V                                             % 1.2., H           ",
"          3.4.5.H | 6.                                            7.8.y 9.0.a.%                                               s b.c.d.s         ",
"        . e.f.b.g.6.                                            . ^.h.i.j.k.l.'                                                 @ M A ~.        ",
"        1 m.n.o.p.                                              / a.q.r.s.t.u.'                                                 { v.w.x.y.      ",
"        # z.A.B.C.                                              . A D.E.F.G.H.~                                                 { I.0.J.g.      ",
"        '.K.L.M.N N.%                                           { O.P.Q.R.S.T.~.(.                                          / : U.! J.V.V       ",
"        / r W.X.Y.w Z.\`./ { {                                   /  +.+++@+#+T.\$+|                                 / / / %+&+) *+=+#+T.-+;+      ",
"        ~ 1.>+,+'+)+!+~+{+]+^+/+4 *.R : H . / / . . . H H H     ~.(+_+:+<+#+[+}+|+C.~ / H H . / / / H 1 : R *.& Z.* 1+2+3+4+5+6+7+[+d ' 8+      ",
"          9+o.v.w.0+a+h.b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+h U.r+  s+t+u+v+w+x+w.y+z+s d.p+p+A+B+C+D+5.E+F+G+H+I+J+K+L+M+N+O+G.P+Q+T.%.s (.        ",
"            % : * R+S+T+U+V+W+X+Y+Y+Z+.+\`+ @.@+++@@@#@\$@%@&@*@g.a =@-@;@>@,@}.d.y.' '@)@!@)@~@{@]@^@]@/@/@(@_@:@<@[@}@P+P+|@A o+1@; 2@6.        ",
"                ' r+3@n+Z 4@S.5@6@7@8@9@0@a@c+u+u+b@c@d@-@e@R f@g@h@i@j@k@l@m@n@V ; o@p@q@r@s@t@(@u@v@w@x@y@z@A@A@A@#+S+w B@a s  .C@6.          ",
"                  D@; H E@F@I.o@J.}@x+G@H@I@J@K@L@M@N@O@i@P@> f@Q@R@S@T@U@V@W@o+% g.X@Y@Z@\`@ #.#+#@###\$#%#A@7+&#F@[++.#.@ '  .8+6.              ",
"                      G C.' : *#=#!.A w.4@x+7+7+-#-#;#>#,#'#s )#Q@!#~#{#k.7+]#^#% y./#(#_#:#d.7+-#-#\$#W@<#I.Z - /+r+s y.| [#6.                  ",
"                            G ,.% ~ \`.y+- I.A }#\$#%#|#1#2#3#'  .\` 4#5#6#7#7+k@n@V ,.8#9#0#a#d -#m@I.w a.j # > b#C.c#d#6.                        ",
"                                    | C.; ~ e#f#W@A@g#Z@h#v.; i#..j#k#l##.%#m#d.C. .\` n#o#p#q#A@r#a { ' C.s#B 6.6.                              ",
"                                          8+g.V.=#P+t#_#u#o+V v## w#x#y#x+A@z#/+A#O B#C#D#E#F#A@[+&.G#6.6.                                      ",
"                                            H#/+z#I#J#0#K#^.)#2@: L#M#N#V@P+O#4 p.P#%+Q#R#S#7+,@+.' C@                                          ",
"                                              T#O#Q U#V#W#>.X#B ~ Y#Z#\`#7+P+I.\$+c#  /  \$.\$+\$-#@\$#\$g.6.                                          ",
"                                              \$\$I.Q %\$D#&\$Z.5   s *\$=\$-\$A@Q I.~.2@  { ;\$>\$,\$'\$m#)\$C.                                            ",
"                                              . w Q !\$~\${\$]\$s#  s , ^\$/\$P+Q w ~ (\$  ~ _\$:\$<\$Q w.[\$ .                                            ",
"                                              { O#A@}\$|\$1\$%+G   ' X@2\$3\$Q P+4\$' C@  5\$w 6\$7\$8\$[+*@9\$                                            ",
"                                              { ^#S.0\$>\$a\$/ b\$  ' V.6\$c\$8\$-#!.'     s a.d\$e\$f\$w : 2@                                            ",
"                                              n ^.J.g\$h\$i\$~ 8+  % j d\$j\$k\$#.a.g.    ' l\$m\$*\$n\$v.s d#                                            ",
"                                                o\$F@n+p\$^ s C@    *#m\$q\$n\$0.|.y.    ' Q@r\$r#A@!.' 6.                                            ",
"                                                B.u.s\$t\$v.'       '.r\$u\$v\$w\$)\$,.      9 x\$T y\$<#g.                                              ",
"                                                1 M =#z\$}#g.      1 A\$3#v\$}#B\$5       C\$2.D\$D\$E\$C.                                              ",
"                                                / I.@\$F\$h V       . G\$w H\$u.N s#      N '@I\$}#J\$;+                                              ",
"                                                { r W@;\$d C.      n K\$T L\$r#: (.      %+M\$S.n+\$\$c#                                              ",
"                                                { - I\$N\$Z.A#      { l.6+O\$4\$> B       . T.P+[+. b\$                                              ",
"                                                ~ P\$J.'@C\$p.      { X@J.H\$u.~ d#      / o@8\$4\$~ d#                                              ",
"                                                  g@o+Q\$N c#      ~ U.J.8\$+.' 6.      { +.F#o+' 6.                                              ",
"                                                  o.+.T.~.R\$      { %.D\$V@<#%         ~ B@4@#\$g.                                                ",
"                                                  %+u.4\$. 8+        \$ F@7.U.V         { S\$}##.C.                                                ",
"                                                  / O#1+~ [#        a T\$|.j C.        { * K\$*# .                                                ",
"                                                  { u.v.'           \$\$!.U\$9 A#          V\$W\$# |                                                 ",
"                                                  { X@r ;           H 4\$}#}+p.          X\$N\$1 G#                                                ",
"                                                  { Y\$) g.          . r 1+'.v#          B#! ~ Z\$                                                ",
"                                                    E@* H#          > +.I.1 G#          \$\$}.'                                                   ",
"                                                    N 9 C.          ~ F@M { d#          : = g.                                                  ",
"                                                    1 R  .          { #\$! s C@          > \$\$y.                                                  ",
"                                                      %             { V.O#'               '                                                     ",
"                                                                      y+) g.                                                                    ",
"                                                                      a /#V                                                                     ",
"                                                                      '.E@C.                                                                    ",
"                                                                      1 %+ .                                                                    ",
"                                                                        i                                                                       ",
"                                                                                                                                                ",
"                                                                                                                                                ",
"                                                                                                                                                "};
_EOF_
}
